### ISSUE TITLE
Uploading a binary

### ISSUE THREAD

**Issue by ozwaldorf** [isdrupter/busybotnet#8]
How do I upload the binary to a router? Is there 1 binary that I can upload?

**Comment by isdrupter** [comment]
You have to compile the binary for the router yourself. There are mips and x64 binaries precompiled currently in the binaries directory, but routers come in many different architectures. You need to figure out what architecture the target device is running and cross compile busybotnet for it using either a toolchain such as buildroot, or a chroot like QEMU. Than you can upload it over tftp, or perhaps with wget. It really depends on the device in question, and on what you have available to transfer files with on the device.

**Comment by kernelzeroday** [comment]
Hello,

Busybotnet can be compiled to a number of architectures, please figure out which one is relevant for your environment using a combination of 'file' '/proc/version' 'realelf -a' and 'objdump' to figure out which cpu arch your environment is and then cross compile for that cpu. For instance, mips or mips32el or armel or armhf or whatever. As for uploading to your router, that depends on your router. many routers will provide you with a basic busybox environment that may or may not have a tool like wget, ftp, tftp, or netcat. 

Busybotnet compiles into a single binary. After you run make you will see both the regular and unstripped debugging executables in the build folder. that is the only binary you need for everything. 

Enjoy

**Comment by ozwaldorf** [comment]
@kernelzeroday @isdrupter  Thanks!
